spring:
  datasource:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/bulk_study?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&profileSQL=true&logger=Slf4JLogger&rewriteBatchedStatements=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        use_sql_comments: false
        generate_statistics: true
        order_inserts: true # batch insert
#        order_updates: true # batch update
        jdbc:
          batch_size: 4
#          batch_versioned_data: true # batch update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    open-in-view: false

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: OFF # TRACE